#端口
#应用名称
#eureka
server:
  port: 11111
spring:
  application:
    name: TopicService
  datasource:
    url: jdbc:mysql://39.99.173.233:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true   #test是数据库的库名
    #mysql-connector-java5使用：jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql-connector-java5使用 com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 30000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

mybatis:
  type-aliases-package: com.cgzj.pojo
  mapper-locations: classpath:mapper/*Mapper.xml