server:
  port: 10010
spring:
  application:
    name: api-gateway
zuul:
  prefix: /api
  routes:
    alltest: /All-Test/**
    serviceChat: /serviceChat/**
    serviceCourseManager: /serviceCourseManager/**
    serviceHomework: /serviceHomework/**
    serviceUserCenter: /serviceUserCenter/**

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka